# Generated by Django 5.2.8 on 2025-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VINProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='מספר VIN')),
                ('status', models.CharField(choices=[('PENDING', 'ממתין'), ('PROCESSING', 'מעבד'), ('COMPLETED', 'הושלם'), ('FAILED', 'נכשל')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'עיבוד VIN',
                'verbose_name_plural': 'עיבודי VIN',
                'ordering': ['-created_at'],
            },
        ),
    ]
